all:tcpselect client tcppoll tcpepoll

tcpselect:tcpselect.cpp
	g++ -g -o tcpselect tcpselect.cpp 
client:client.cpp
	g++ -g -o client client.cpp 
tcppoll:tcppoll.cpp
	g++ -g -o tcppoll tcppoll.cpp 
tcpepoll:tcpepoll.cpp
	g++ -g -o tcpepoll tcpepoll.cpp 

clean:
	rm tcpselect client tcppoll tcpepoll